### ISSUE TITLE
Duty->Consequence

### ISSUE THREAD

**Issue by riannella** [w3c/poe#209] opened 2017-07-04 00:08 UTC
Proposal for "consequence" for not fulfilling a Duty (from Sabrina/Simon by 14 July).
And possibly "Regulation" policy type.

**Comment by riannella** [comment] 2017-07-04 03:18
Has anyone documented the information model underpinning the European General Data Protection Regulation ?

**Comment by vroddon** [comment] 2017-07-06 08:29
For the first: are we talking about remedies?
For the second: yes, there are several ontologies, I guess Sabrina has gone further writing them in terms of ODRL. ..

**Comment by simonstey** [comment] 2017-07-06 09:24
> For the first: are we talking about remedies?

kinda, but something more general.. 

**Consequence:** If you do _X_ you are obliged to do _D1_. If you did _X_ but fail to prove that you have done _D1_, you are obliged to do _D2_.

**Remedy:** If you do _X_ you are obliged to do _D1_. If you did _X_ but fail to prove that you have done _D1_ as well, you are obliged to do _D2_ **instead of** _D1_.

**Comment by riannella** [comment] 2017-07-07 04:03
You will notice in ODRL 2.1, that Remedy was applicable to Prohibitions:
https://www.w3.org/community/odrl/model/2.1/#section-53

So for consequence - you still **must** do D1 ?

And is remedy then the same as "do at least one of D1 or D2" ?

**Comment by simonstey** [comment] 2017-07-07 06:11
> You will notice in ODRL 2.1, that Remedy was applicable to Prohibitions:

ah yes, but also duties:
> Not only can a Prohibition have a Duty attached to it as a remedy, **even Duties themselves may have remedies,** ...

--------------
> So for consequence - you still must do D1 ?

we would allow duties to refer to other duties, and would only state that those other duties become effective (for the enclosing rule/policy) as consequence for not fulfilling the duty that links to them.

Since duties are in effect as long as they haven't been fulfilled, _D1_ is still in effect.
> And is remedy then the same as "do at least one of D1 or D2" ?

1. do _D1_
2. if you fail to do _D1_, you have to do _D2_ instead (you can't do _D2_ unless you know that _D1_ wasn't fulfilled)

**Comment by simonstey** [comment] 2017-07-19 10:36
proposal: https://www.w3.org/2016/poe/wiki/Duty_Relations

**Comment by riannella** [comment] 2017-07-21 04:25
Some thoughts...

> => :permission1 is only in effect if :duty1 is considered to be fulfilled. Exercising :permission1, but failing to prove the fulfillment of :duty1 results in :dc1 becoming effective.

So what then does it mean for a Permission to be "in effect", if we now allow a Permission to be exercised without the fulfilment of the Duty.

Does this mean I can also now exercise a Permission (ignore the duty) even when there is no consequence Duty defined.

Perhaps we need to explicitly state that you can only exercise a Permission and not fulfill the Duty if there is a consequence declared as well.

Same for Prohibition.

@fornaran also  indicated in #191 that violating Prohibitions may lead to reputation issues. So we should state that violating a Prohibition is a design mechanism of the odrl policy language and does not mean you are being naughty 😸

**Comment by vroddon** [comment] 2017-07-31 12:57
I agree with the model in https://www.w3.org/2016/poe/wiki/Duty_Relations

First objection. The choice of "`odrl:consequence`" may be confusing for a reader facing these triples:

```
:policy1 odrl:obligation :duty2 .
:duty2 odrl:consequence :dc2 .  
```
It seems as if doing :duty2 leads to :dc2, whereas the actual meaning is "using :policy1 without having done :duty2 has :dc2 has a consequence". Perhaps a better term is needed.

Second objection: the consequence may not be initiated by the breacher. 
A punishment would not be a duty of the breacher, but some action the punisher may or may not execute. In this sense, it would not be a "duty", but more a "permission" ....

But in general, the proposed change is a good one!

**Comment by riannella** [comment] 2017-08-01 05:17
I have added the consequence and remedy properties to the Information Model (see 2.5.3 Duty section and the three subsections) and also added to the Vocab (and JSON-LD/XML).

(see above link to commit for diffs)

Please comment to make sure we have captured the essence of the proposal.

**Comment by vroddon** [comment] 2017-08-07 12:42
I still do not understand fact that a "consequence" is a "duty".

Does anybody else agree?

**Comment by riannella** [comment] 2017-08-07 13:33
A consequence is a **relationship** between a Duty and Permission's Duty.
If means if the latter is not fulfilled, and the permission is exercised, then you must do the former.

**Comment by vroddon** [comment] 2017-08-07 15:11
> then you must do the former.

Well, this is what I think that can be generalized:
a) you must do the former
... or ....
b) I am entitled to do something else on you (e.g., ban you from you organization)

**Comment by vroddon** [comment] 2017-08-08 01:44
I have made a simple proposal, but with a clear rationale, here:

https://www.w3.org/2016/poe/wiki/Duty_Relations

(I did not change previous text, but added a "second version"). For a fast glimpse, see the figure below.

<img width="294" alt="version2small" src="https://user-images.githubusercontent.com/5434597/29052676-9469a52a-7bb9-11e7-9d11-ea09d41c4206.png">

**Comment by riannella** [comment] 2017-08-08 05:15
@vroddon 

P1/P3:  where it says "But if you navigate more than 1Gb" - how is that expressed in ODRL?
A constraint?


P2: I can express that now as:

```
   "prohibition": [{
        "target": "myphone",
        "assigner": "telco",
        "assignee": "me",
        "action": "p2p-traffic",
        "remedy": [{
            "action": "report-police",
	    "assignee": "telco"
            }]
        }]
    }]

```

I think the reason that consequence/remedy refer back to a Duty is because it means you **must** then do something, as opposed to _may_ or _may not_ do something.

What use cases state that if you **fail** something, then you are **permitted** to do something else?

**Comment by fornaran** [comment] 2017-08-08 08:11
As discussed is this paper at page 6:
http://drops.dagstuhl.de/opus/volltexte/2007/909/pdf/07122.FornaraNicoletta.Paper.909.pdf
when there is a violation (an obligation is not fulfilled or an action that is not permitted is performed) the sanctions may be related to:
- the actions that the misbehaving agent itself has to perform against a violation,
- the actions that certain agents (different from the misbehaving agent) are authorized to perform only against violations

In P1 is Vodafone that gets the power to lower the speed. Given that in ODRL the institutional power is not modelled it is possible to simply model it as a permission for Vodafone to lower the speed.

**Comment by vroddon** [comment] 2017-08-08 11:40
I see two advantages of the second version: 
(a) the cases covered by the second are a superset of those from the first (P2 can be still expressed) and...
(b) it uses a single property instead of two, avoiding as well potentially conflictive terms like "remedy"

**Comment by vroddon** [comment] 2017-08-08 11:50
I forgot say that I agree with @fornaran and to thank her for the reference.
And I see now two interesting points in @riannella 's comment:

**1) Domain of failure**
I had only foreseen that a failure is activated:
* When a duty is not satisfied (and yet the permission's action acted)
* When a prohibition is violated

I had have totally missed:

* When a permission is exercised but the constraints not satisfied

In order to be general, I would include failure in this case, too. The domain of the property 'failure¡ should be "rule" and the range "rule". Even simpler model! Yet I would keep the three possibilities in the text definition.

**2) Conditional rules**
Let us consider P2, which I model below using version 2--although the problem is also common to version 1.
```
  ex:p1 odrl:prohibition [
    odrl:action ex:p2p ;
    odrl:assignee ex:me ;
    odrl:assigner ex:telco ;
    odrl:failure [
      a odrl:Duty ;
      odrl:assignee ex:telco ;
	  odrl:action ex:report-police 
      ]	
  ]
```
If the RDF graph is queried about "how many duties there are", the failure/remedy duty here will be present. But we would like this will only to be true conditionally. Consequently, we have to add something to the Duty (in either version of the model) to indicate "only conditional". 
In order to count in-force duties, we can rely on sentences like "Duties that are independent, not object of any odrl:failure" but this may not be the best. The alternative would be to indicate explicitly that the duty is only conditionally in effect. I am neutral about either option.

**Comment by vroddon** [comment] 2017-08-08 12:10
Please see the ammended proposal here:

https://www.w3.org/2016/poe/wiki/Duty_Relations#Duty_Relations_.28Third_version.29

**Comment by simonstey** [comment] 2017-08-09 10:51
> When a permission is exercised but the constraints not satisfied

in which case we would assume that everything that's not explicitly permitted is prohibited by default. do we want that?

**Comment by vroddon** [comment] 2017-08-09 15:16
Well, it is not the case. 
"You can drink if you are above 18" implicitly entails that you cannot if you are under 18.

**Comment by simonstey** [comment] 2017-08-09 15:33
> Well, it is not the case.
"You can drink if you are above 18" implicitly entails that you cannot if you are under 18.

no.. that's OWA vs CWA. 

you only know that if you are over 18 you are allowed to drink and unless there's a general prohibition to drink you simply don't know whether someone under 18 is permitted or prohibited to drink.

absence of permission != prohibition (and vice versa)

**Comment by vroddon** [comment] 2017-08-09 15:39
Yes, I know. It is a key issue. 
But in both cases this is the behaviour that can be expected once a permission with constraints is given.

**Comment by simonstey** [comment] 2017-08-09 15:46
> But in both cases **this is the behaviour that can be expected** once a permission with constraints is given

probably, yes.. but not enforced. it depends on the implementation.

btw. this would also affect odrl:implies

**Comment by vroddon** [comment] 2017-08-09 15:50
Please note that this is what is said in the current wording of section 3.8 in the Information Model (boldface is mine):

> Constraints must be checked by processings system at the time of executing the relevant action. If the constraint is satisfied (ie the logical expression is true) then the action becomes valid for the enclosing Rule. **If the constraint is not satisfied, then the action is not valid for the enclosing Rule**.

I don't see the change about "implies". Example?

**Comment by riannella** [comment] 2017-08-10 02:36
@simonstey @sabrina the proposal from @vroddon is to replace both consequence/remedy properties with a single "failure" property (from Rule to Rule).

What do you think of  this proposal?

Will it still meet your use cases (for regulations)?

**Comment by riannella** [comment] 2017-08-14 06:14
One negative of a single failure property is that it would not capture the main difference between consequence and remedy in that the former **adds** more rules, and the latter is a new rule.

Also, what is the semantics of Permission-->failure-->Permission ?

**Comment by vroddon** [comment] 2017-08-14 12:21
> Also, what is the semantics of Permission-->failure-->Permission ?

The second permission is not valid unless the first permission is a failure (e.g. one ore more of the actions are acted without respecting the constraints). The assignee of the second permission will be in general a different one from the second (e.g. ability for other to punish)

**Comment by riannella** [comment] 2017-08-14 23:41
As per: https://www.w3.org/2017/08/14-poe-minutes.html

Add the "failure" property as an abstract property. (Profiles can sub-prop it and refine semantics).

Make consequence and remedy sub-props of failure.

**Comment by vroddon** [comment] 2017-08-14 23:46
My apologies on a previous comment. The following text had been unadvertedly quoted from the February Working Draft. The new wording is far more clear.

> Constraints must be checked by processings system at the time of executing the relevant action. If the constraint is satisfied (ie the logical expression is true) then the action becomes valid for the enclosing Rule. If the constraint is not satisfied, then the action is not valid for the enclosing Rule.

**Comment by riannella** [comment] 2017-08-15 00:11
Another option for "failure" is more simply "notMet" - that is, the Rule has not been met (as opposed to the Rule has failed).

Or "notAdhered" to

**Comment by riannella** [comment] 2017-08-17 01:42
Added the abstract Failure property

**Closed as completed** 2017-09-01 05:46 UTC
Labels: To Be Closed, Model
