### ISSUE TITLE
Model clarifications

### ISSUE THREAD

**Issue by riannella** [w3c/poe#162] opened 2017-05-02 04:01 UTC
@aisaac

3. I have some remarks/questions about the explanation of what POE elements are, which may be a bit more than editorial comments. It could be that the model is not clear, or it could be that my understanding of relationships between POE elements was hindered by editorial choices. Here’s the list of what I noticed:

- Permission, Prohibition and Duty are defined in 1.4 as ‘A set of Actions that are allowed/forbidden/obligatory’. This is easy to read, but it hides the fact that The POE ontology actually defines these classes as subclass of Rule, not Action. And in fact it just conflicts with the definition of Action in the same section: “An operation that can be allowed by Permissions, disallowed by Prohibitions, or made obligatory by Duties.” An Action is allowed by actions? No, in the model an Action is allowed by a Rule. So it would be more exact to change the definition and maybe change the identifiers and labels of these classes, to “PermissionRule”, “ProhibitionRule” and “DutyRule”.

- section 3.1 (and probably others afterward, like the bullet list for the Constraint entity in 3.8) use the notion of reference in a way that is quite confusing wrt. what happens concretely in POE. A resource doesn’t really ‘refer to a UID’ when this ID is the basic identifier of the resource. If I’m right, then the wording could be more direct simpler, e.g. ‘have a UID identifier’ instead of ‘refer to the uid identification of the Policy entity’. And ‘have an X attribute’ instead of ‘refer to the X attribute’.

- in fig 1, “Relation”, “Inheritance” and “Role” are represented by boxes, which lets one think they are ‘reified’ (following the n-ary relationship pattern at https://www.w3.org/TR/swbp-n-aryRelations/). Which is not the case: these are simple binary relationships represented with RDF properties. Section 3.2.1 says that “The Relation entity is an association class” but this is contradicted in the same section by the note that mentions “a sub-property of the relation property”. Which of these characterisations is the right one? Can’t the Information Model reuse the simple wording of 4.7.2 in the POE vocabulary (“Relation is an abstract property” https://www.w3.org/TR/odrl-vocab/#term-relation)?
The same remark applies when Role is defined as “an association class” or an “entity” (in 3.3.1).

- ‘Policy Composition” in 3.1.1 is misleading. This is not about composition of policies, it’s about composition of elements within a policy.

- in 3.1.3 it is said that conflicts may arise between Permissions and Prohibitions. Not with Duties? One could easily imagine duty-related conflicts.

- in 3.1.5, what is ‘state information’ for policies?

- The Scopes remain mysterious to me after reading section 3.2.2 and 3.3.2.
In example 17 JPEG is given as an example of scope, but what exactly is intended here? When one says that a catalogue mentioned as Asset has the JPEG format as scope, does it mean that the catalogue is already made of JPEG files, or is it that the policy should target only the sub-set of JPEG files in the catalogue?
In 3.3.2 the examples of scope again are ambiguous on whether it’s about ‘additional metadata for an asset/party’ (i.e. knowing that a Party is a group) or ‘modifying what is meant by the asset/party’ (selecting the “18+” in a group).
Maybe more concrete use cases would help. The only occurrence of ‘scope’ in the POE Use Cases (https://www.w3.org/TR/2017/WD-poe-ucr-20170223/#POE.UC.21) doesn’t say much to me.
Finally, if scopes can be about changing what is meant by the Asset or the Party, this seems quite dangerous to to it while keeping the original identifier for the Party/Asset. When gathering all the facts for that URI across different policies, this may lead to unwanted side-effects. Why not create new URIs for the Asset/Party with altered scope? Using the faculty example, that would mint minting a URI for the faculty staff among users, rather than hijacking the URI for all users. Same for selecting adult among friends in example 19. Why not minting http://example.com/user44/friends/Over18 or using a blank node?
When POE wants to alter a Policy, it does recommends the creation of a new one, probably with an odrl:inheritFrom between them, doesn’t it? The new URI for the altered Asset/Party (or blank node) could still refer to the original one (via something like odrl:inheritFrom) and to the scope itself (“18+” can still be an attribute of the new URI). This would mean moving to adopting the pattern of ‘selector’ as used in Web Annotation (https://www.w3.org/TR/annotation-model/#selectors).

- in 3.3 I don’t understand why a lot of the wording refer to function being a reference “from the Party” (“The Party entity MUST refer to the function”). “The Role entity has the following attributes” is also misleading (see previous comments on associations)...
It’s not the Party that specifies the function. It is the Policy/Rule that involves the Party that defines its function. In other terms, the function is not essential to the Party itself. So it makes quite some sense to find the function represented as it is in example 18, i.e. as attributes of the permission (assigner, assignee). But why all the confusing wording before? Am I missing anything?

- in 3.4. The wording with “The Permission entity”, especially in “The Permission entity specifies the Actions”, hints that there is only one permission per policy, which refers to all the actions allowed. Is it really the case in the abstract Information Model? In the same section one can read “An ODRL policy MAY contain at least one permission”, and indeed in the RDF serialization there can be several instances of the Permission class attached to a policy. So if there can be several permissions then nearly all occurrences of “The permission” should be changed into “a permission”. And “The Permission entity specifies the Actions” into “A Permission entity specifies Actions”.
A similar comment applies to section 3.5 on Prohibition and 3.6 on Action. Basically to all the wording that hints at the existence of cardinality constraints, which are not true in reality.

- in 3.6 “Other role function values for Party MAY be used.” Which ones? A couple of examples could be useful.

- in 3.8 there is no rational given for rightOperandReference. One may think it’s perfectly fine to use rightOperand both for literal values and URIs, directly. Why wasn’t it the case? And why do example of right operand with URIs not using rightOperandReference, like https://www.iso.org/obp/ui/#iso:code:3166:IT in example 25?

- for examples 12, 13 and 14, is it possible to have a bit more motivation (or a use case) for the inheritance of target assets for policies? The idea that policy inheritance would be used to ‘stack’ targets seems a bit strange. The case for stacking permissions, obligation and duties, or assignees, seem much stronger. I’m definitely not an expert, so I may miss something obvious. I thought I’d flag this remark, in case.

**Comment by riannella** [comment] 2017-05-05 03:18
We have made a major update to the IM that addresses many of these comments now.

See this commit e055b79b52922eb52942a7622cebe25df3c091f1

1 - covered in commit

2 - removed all the "refers"

3/4 - covered in commit

5 - The ODRL conflict strategy only deals with perms/prohit conflicts. We have issue #138 discussing this now.

6 - Added more details.

7 - Updated the two scope sections. One reason for this feature is that there may not be the ability to identify the scoped-group with a URI.

8/9 - covered in commit

10 - Done

11 - Updated the text. That example is a not rightOperandReference, it is that actual URI that is compared to the leftOperand. That is, you do not deref the "IT" uri to get the value.
 
12 - Updated the use case examples

New commits 3a11111d80d6db29d13a10e88d99aff6346ca1cf

**Comment by aisaac** [comment] 2017-05-17 23:04
1. OK

2. OK

3. OK

4. I am not sure the commit addresses my point. "Policy Composition" is still the heading of (the new) section 3.7. May complain is that this expression is ambiguous. On the one hand, it can be understood as discussing the contents/components of a Policy. But one could also understand it as an attempt to compose different Policies together, which is not the case. (In a way, the new first sentence "A Policy MAY contain multiple Rules [...]" is much clearer about the scope of the section)

5. I see that Issue #138 did not lead to any major change, so I suppose my comment still applies?
In any case I don't see why *not* restricting conflicts to only Permissions and Prohibitions would harm POE. The restrictions on permissions and prohibitions seems like a case of ontological commitment that brings little added value.

6. OK

7. The new text clarifies the intention behind scopes and their use case.

I now have to flag them as a case of very bad RDF practice of 'hijacking' identifiers. Namely, I expect http://example.com/media-catalogue to be the identifier of the full catalogue. It is quite absurd to state that this uid is both the identifier of the full catalogue and the identifer of the 'scoped' part of itself. You say that this is motivated by the fact that the part of the cataloguer. This is a valid requirement, but no reason to abuse the original identifer. In fact it should not be 'uid' that is used to refer to the full catalogue, but some other property. Which is why was suggesting to look at the selector pattern in Web Annotation, which can meet your original requirement in a much harmless way.

I have a similar reaction to the example in 3.3.2. It is quite absurd to imagine that a Party that "is a single individual" or "represents a group of individual members" could be anything else. This is not really a job for scoping the meaning of a resource, but typing it, truly. Why not having used @type?

Actually the example with the party allows me to show the absurd side effect of the current pattern.
Imagine a Policy that targets the sub-group of user44's friends that are over 18. The representation of this Policy will include the following, as in example 8:
{
    "uid": "http://example.com/user44/friends",
    "scope": [ "Group", "http://example.com/people/age/18+"]	
}

Imagine that at the same time there is another Policy that targets the sub-group of user44's friends that are below 18. I suppose that this will lead to a representation including something like
{
     "uid": "http://example.com/user44/friends",
     "scope": [ "Group", "http://example.com/people/age/18-"]	
}

Now if one loads the representation of these two policies in an RDF store, this will lead to the following description for the group of friends of user44
{
     "uid": "http://example.com/user44/friends",
     "scope": [ "Group", "http://example.com/people/age/18+", "http://example.com/people/age/18-"]	
}

Am I wrong? If not, then what does this mean? Note that this wouldn't be fancy inference, just the application of what the RDF data model is. It is bad to hijack identifiers to represent something that they are not really meant to represent.

Btw 3.3.2 has a typo "The scope feature is useful is there is no ability to directly identify the intended Party with a uid identifier"

8/9. OK

10. OK

11. About https://www.iso.org/obp/ui/#iso:code:3166:IT: using what looks like a URI for a value that didn't have to be de-referenced is really quite unfortunate!
Also, I still don't understand the rationale for rightOperandReference. This is for the cases where the value is a URI that will be de-referenced?
In this case:
- it could be alright to have rightOperand used both with literal values and URIs. My comment here has not been answered
- I really don't get that "dataType indicates the type of the rightOperand/Reference, such as xsd:decimal or xsd:datetime" as is written in the new 3.6.1. If it's a URI, then it's not really expected to have a dataType like xsd:decimal or xsd:datetime
I guess examples may clarify whether I'm completely misunderstanding what happens here, or there is something really fishy with rightOperandReference

And in fact now that I read these sentences and example with datatypes I'm puzzled even with the use of datatypes with rightOperand. I'm not sure why POE introduces its own dataType property and does not re-use one of the options for data types in JSON-LD at https://www.w3.org/TR/json-ld/#typed-values


12. I really like the new examples, they really put the interest of inheritance clear!
There's just a typo on 'assinger' and the sentence "and allows the archive and annotate Permissions and the aggregate Prohibition." is strange (one would 'allow a Prohibition'?)

**Comment by riannella** [comment] 2017-06-01 01:06
4) What if we named the section "Policy Rule Composition" ?

5) Can  you give an example of a duty-related conflict?

7) We have now addressed this with the Asset/PartyCollection. Only assets/parties of this type (indicating multiple members) can have constraints (was scopes).

11) We want to 'express' datatypes in the model. We state you can use rdf:datatype: https://w3c.github.io/poe/vocab/#term-dataType
Added @type for JSON.

Yes, rightOperandReference is literally the  case where you must deref the URI.
So these are two different values in a Constraint
rightOperand = https://www.iso.org/obp/ui/#iso:code:3166:IT
rightOperandReference = https://www.iso.org/obp/ui/#iso:code:3166:IT

The first is the actual string of the URI that you compare to something, the second, you must deference, and use that value of what is returned in the expression.

12) fixed the wording

commit: e54a82fdd45044a6f547b60872f6ec78a164d58a

**Comment by aisaac** [comment] 2017-06-06 11:04
4. Maybe while reading the next version at once I will still feel uneasy with 'composition' itself. But right now it seems a better wording, anyway!

5. Maybe a policy that (possibly by inheritance) asks the assignee to attribute the creator and at the same time to anonymize the asset?
Or a policy that declares inheritance from CC-BY but requires compensation for commercial use?
They will all look a bit absurd of course, but I guess it's the essence of conflict :-)

6/7. Maybe there's some confusion? #6 was already ok for me. #7 was the hard one.
Adding @type and using constraints brings clarity. It still doesn't solve the essential issue of URI hijacking, though. The problem lies in the resources created/re-used in the constraints, not their types or their statements. As long as different statements are made about the same URI, then confusing arises and the same issues of 'conflating triples' will happen, as I've put in example (just replace scope statements with statements about constraints and types in my example above).

11. (this is both discussions on data types and right operands URIs are relevant)
data type: https://w3c.github.io/poe/vocab/#term-dataType looks much better, but I still don't get why it's a MAY not a must. This is opening the door to several (quite different) representations of the same information in RDF. And as a matter of fact example 14 (and maybe others) still don't use the right RDF pattern. Do you plan to update them?

righOperand vs rightOperandReference: OK I think I get it now. I would still urge you to go one step further in clarifying this modeling, which can be confusing to the reader: what I can think of now:
- declaring rightOperand a Datatype property (in the OWL sense).
-  saying somewhere that even when rightOperand is used with URLs, these are to be considered as strings
- changing the definition "The right operand in a constraint expression" at https://w3c.github.io/poe/vocab/#term-rightOperand (and maybe elsewhere where the property is mentioned?). Right now it reads too generic - as if it was also covering the cases covered by rightOperandReference

**Comment by riannella** [comment] 2017-06-07 01:50
@simonstey what do you think about 5) above?

**Comment by riannella** [comment] 2017-06-07 02:40
4) updated title

11) mandatory now
I now think we can't directly use @type (in JSON-LD) as that is the type for the entire node.
So you would need to express:
              "rightOperand": "100.00",
              "dataType": "http://www.w3.org/2001/XMLSchema#decimal",
as:
   "rightOperand":
  {
    "@value": "100",
    "@type": "http://www.w3.org/2001/XMLSchema#decimal"
  }

Updated rightOperand/Reference narrative/definition

commit: 79d75d4695205c9dd75c023516f15185f9ea87c2

**Comment by simonstey** [comment] 2017-06-07 06:08
> @simonstey what do you think about 5) above?

I definitely agree with @aisaac here. Even more so, since Duties can now have **any** Action as their `odrl:action` and not just ones that can't be used by Permissions/Prohibitions and vice versa.

Btw we state in [2.5.3 Duty](http://w3c.github.io/poe/model/#duty):
> It is assumed that **any** assigned Party has the appropriate permissions to perform the Duty Action.

Which is too restrictive, as not **any** assigned Party needs to have permissions to perform the Duty Action but only the ones that actually have to fulfill the obligation.

e.g. `ex:Bob` permits `ex:Alice` to reproduce `<http://example.com/asset:9898>` but only if  `ex:Alice` plays `<http://example.com/asset:1>`:

```turtle
<http://example.com/policy:01>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/asset:9898> ;
        odrl:action odrl:reproduce ;
        odrl:assigner ex:Bob ;
        odrl:assignee ex:Alice ;
        odrl:duty [
             a odrl:Duty ;
             odrl:action odrl:play ;
             odrl:target <http://example.com/asset:1> ;
        ]
    ] .
```
to be able to fulfill her duty, **only** `ex:Alice` needs to be allowed to `odrl:play` `<http://example.com/asset:1>`. So even if `ex:Bob` is prohibited to play `<http://example.com/asset:1>`,  there's no conflict as `ex:Alice` is still able to fulfill her duty:

```turtle
#no conflict
<http://example.com/policy:02>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/asset:9898> ;
        odrl:action odrl:reproduce ;
        odrl:assigner ex:Bob ;
        odrl:assignee ex:Alice ;
        odrl:duty [
             a odrl:Duty ;
             odrl:action odrl:play ;
             odrl:target <http://example.com/asset:1> ;
        ]
    ] ;
    odrl:prohibition [
        a odrl:Prohibition ;
        odrl:target <http://example.com/asset:1> ;
        odrl:action odrl:play ;
        odrl:assignee ex:Bob ;
    ] .
```
-------------------------
> Maybe a policy that (possibly by inheritance) asks the assignee to attribute the creator and at the same time to anonymize the asset? Or a policy that declares inheritance from CC-BY but requires compensation for commercial use? They will all look a bit absurd of course, but I guess it's the essence of conflict :-)

fwiw, those wouldn't cause conflicts :)

**Comment by riannella** [comment] 2017-06-08 01:16
So we can change this:

> It is assumed that any assigned Party has the appropriate permissions to perform the Duty Action.

to

>  The assigned Party MUST have the permission to perform the Duty Action.

 With these semantics, there will never be a conflict with the duty action.

**Comment by riannella** [comment] 2017-06-12 02:06
Updated as per above: 1c55587d1e111c7738a5713388a83458dd693b45

**Comment by simonstey** [comment] 2017-06-13 06:01
>So we can change this:
>  _It is assumed that any assigned Party has the appropriate permissions to perform the Duty Action._
>
>to:
>    _The assigned Party MUST have the permission to perform the Duty Action._

hmm.. I'm not 100% sold on the "the assigned Party" part, as it's still not clear to which party this actually refers to, cf: [Duty](https://w3c.github.io/poe/model/#duty):
> A Duty MAY have **one or more** assigner and/or assignee function roles **undertaken by Party entities.** If the functional roles are not specified in the Duty, then the respective functions are assumed to be the same as in the referring Permission. Other types of function properties for Party MAY be used (for example, Compensated Party or Tracking Party). 

what do we actually want to say with that? 
Is it:

a) the parties responsible for fulfilling a duty have to have explicit permissions:  
```turtle
<http://example.com/policy:a>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/asset:9898> ;
        odrl:action odrl:reproduce ;
        odrl:assigner ex:Bob ;
        odrl:assignee ex:Alice ;
        odrl:duty [
             a odrl:Duty ;
             odrl:action odrl:play ;
             odrl:target <http://example.com/asset:1> ;
        ]
    ] ;
    odrl:permission [ # ex:Alice needs this permission to be able to fulfil her duty
        a odrl:Permission ;
        odrl:target <http://example.com/asset:1> ;
        odrl:action odrl:play ;
        odrl:assignee ex:Alice ;
    ] .
```

b) each duty comes with implicit permissions, thus, any prohibition contradicting one of those permissions would cause a conflict:
```turtle
<http://example.com/policy:b>
    a odrl:Policy;
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/asset:9898> ;
        odrl:action odrl:reproduce ;
        odrl:assigner ex:Bob ;
        odrl:assignee ex:Alice ;
        odrl:duty [
             a odrl:Duty ;
             odrl:action odrl:play ;
             odrl:target <http://example.com/asset:1> ;
        ]
    ] ;
   # implicit
   # odrl:permission [ 
   #     a odrl:Permission ;
   #     odrl:target <http://example.com/asset:1> ;
   #     odrl:action odrl:play ;
   #     odrl:assignee ex:Alice ;
   # ] ;
    odrl:prohibition [
        a odrl:Prohibition ;
        odrl:target <http://example.com/asset:1> ;
        odrl:action odrl:use ;
    ] .
```

I think it should be b)

**Comment by riannella** [comment] 2017-06-14 02:11
1) Updated the list of Duty requirements to make it clear about the assignee of the Duty

commit: e88abc364ffb53b676770b23ac1f829ffb5d00b6

2) B) is ok, but now (i assume) we now need to update the Conflict Strategy with a new option "duty" as there are three conflicting options (with "perm" and "prohibit") ?

Which also means that we have to remove:

> The assignee MUST have the Permission to perform the Duty Action.

**Comment by aisaac** [comment] 2017-06-18 17:24
There’s still the issue about URI hijacking, but I’m going to continue this in #164 instead as it seems to be where it’s happening.

Definition of rightOperand and rightOperandReference is better, both in the Voc and the IM. Well done.

I think I'm ok with the current use of data types, but their definition (https://w3c.github.io/poe/vocab/#term-dataType) is still strange (“In RDF encodings, use of the rdf:datatype MUST be used. In JSON-LD encoding, the use of @type MUST be used.”). In addition, what’s the use of still minting odrl:dataType if it’s not going to be used in actual encodings? Note that you could keep this section in the POE vocabulary doc could exist without creating a new property.

Re. the issue of duty-related conflicts, I believe that the course of the discussion between @riannella and @simonstey (as well as the changes already made in the IM) should answer my original question. I am not going to interfere any further here!

**Comment by riannella** [comment] 2017-06-19 03:20
Thanks ;-)

**Comment by simonstey** [comment] 2017-06-19 05:49
> Updated the list of Duty requirements to make it clear about the assignee of the Duty
commit: e88abc3 

lets see..

> 1.) A Duty must only be associated with a Permission.

that's not in line with what we discussed in https://github.com/w3c/poe/issues/154#issuecomment-301697412 : 
> Done: 38b945c
Let Set be free :-)

------------------

> 2.) A Duty may be linked to an Asset via a `target` relation property on which the agreed Action must be performed. This does not restrict the sub-properties of `relation` that are used as properties of the Asset.

+ What's the difference between the term **relation** in _`target` relation property_ and _sub-properties of `relation`_? why are the 2 formatted differently?
+ I don't get the second sentence.. What's the rationale behind it?

------------------

> 3.) The assignee(s) of the Permission are the assignee(s) of the Duty.
  4.) A Duty may define different assignee(s) functional roles (than defined in the Permission) that overide the assignee(s) in the Permission for the purposes of the Duty.
  
+ and what about the assigne**r**(s)?
+ if the ass. of the perm. are the ones of the duty, does that mean a policy like the following one has no assignee at all?:

```turtle
<http://example.com/policy:00>
    a odrl:Set;
    odrl:assigner ex:Bob ;
    odrl:permission [
        a odrl:Permission ;
		odrl:assignee ex:Alice ;
        odrl:target <http://example.com/asset:1> ;
        odrl:action odrl:use ;
        odrl:duty [
            a odrl:Duty ;
            odrl:action odrl:play ;
            odrl:target <http://example.com/asset:2> ;
        ]
    ] .
```

+ who are the assignees of the permissions & duties in following examples:

```turtle
<http://example.com/policy:01>
    a odrl:Set;
    odrl:assigner ex:Bob ;
    odrl:permission [
        a odrl:Permission ;
		odrl:assignee ex:Alice ;
        odrl:target <http://example.com/asset:1> ;
        odrl:action odrl:use ;
    ] ;
    odrl:duty [
        a odrl:Duty ;
        odrl:action odrl:play ;
        odrl:target <http://example.com/asset:2> ;
    ] .
```

```turtle
<http://example.com/policy:02>
    a odrl:Set;
    odrl:assigner ex:Bob ;
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/asset:1> ;
        odrl:action odrl:use ;
    ] ;
    odrl:duty [
        a odrl:Duty ;
		odrl:assignee ex:Alice ;
        odrl:action odrl:play ;
        odrl:target <http://example.com/asset:2> ;
    ] .
```

------------------

> 5.) The assignee(s) of the Duty must satisfy the Duty.

+ what does that mean for duties like [ensureExclusivity](http://w3c.github.io/poe/vocab/#term-ensureExclusivity)?

```turtle
<http://example.com/policy:03>
    a odrl:Set;
    odrl:permission [
        a odrl:Permission ;
        odrl:assignee ex:Alice ;
        odrl:assigner ex:Bob ;
        odrl:target <http://example.com/asset:1> ;
        odrl:action odrl:use ;
        odrl:duty [
            a odrl:Duty ;
            odrl:action odrl:ensureExclusivity ;
            odrl:target <http://example.com/asset:1> ;
        ]
    ] .
```

------------------

> 6.) A Duty may define other functional roles (for example, to indicate the compensatedParty or a different assigner).

+ but those can't override?

------------------

> 7.) The assignee must have the Permission to perform the Duty Action.

+ what about assigner(s)?
+ _"must have Permission to perform"_ != _"must not be prohibited to perform"_

**Comment by vroddon** [comment] 2017-06-19 07:51
I think we should re-define ensureExclusivity. Current definition reads:

> To ensure that the Rule on the Asset is exclusive.

Instead, I would say that ensureExclusivity can be defined in a more precise manner, for example:

> To prevent other Assignees from having a permission to perform the same Action over the Asset.

**Comment by simonstey** [comment] 2017-06-19 08:45
https://www.w3.org/community/odrl/vocab/2-1/ said: 

> **ensureExclusivity** 	The Assignee requires that the Assigner(s) ensure(s) that the permission on the Asset is exclusive to the Assignee.

**Comment by riannella** [comment] 2017-06-20 05:45
@simonstey list:

1) Agree. I commented here: https://github.com/w3c/poe/issues/154#issuecomment-301982097
"the duty at the Policy level means what"

I **recommend** we keep the requirement that a Duty can only ref from a Permission.

What do you think @vroddon ?

2) Poorly worded. Fixed.

3/4)
- added the assigners now

policy:00) Who are the assignees: Alice is the assignee of the Permission, and hence the Duty. Bob is the assigner of the Perm (after you atomic-ise the policy) and hence the Duty.
policy:01) Who are the assignees: Alice
policy:02) Who are the assignees: Alice

5) In that specific case, if left as is, Alice must ensureExclusivity of the odrl:use.
Hence, if a policy-maker uses this action, then they should define the assignee of the Duty to Bob.
(Added notes to term)

6) They are not used in the Permission, so should not be overrided  (and not mentioning assigner here anymore)

7) s/Permission/ability/

commit: e0d11bcb4b4a13c967212e44fcecaafe2170527c

**Comment by vroddon** [comment] 2017-06-21 08:52
I would treat it in the same manner as #issue  184 (https://github.com/w3c/poe/issues/184), whichever the result...
(pity that I missed Monday's call ...)

> @simonstey list:
> Agree. I commented here: #154 (comment)
> "the duty at the Policy level means what"
> I recommend we keep the requirement that a Duty can only ref from a Permission.
> What do you think @vroddon ?

**Comment by simonstey** [comment] 2017-06-21 12:06
> Agree. I commented here: #154(comment)
"the duty at the Policy level means what"

for whatever purpose it's used for.. whether it's modeling legislations/regulations or stating that Alice ows Bob 10 euro (she has the obligation to pay him 10€).

>  I recommend we keep the requirement that a Duty can only ref from a Permission.

what's the problem with allowing policies of type Set to have duties?

(tbh, I don't understand why I have to fight for this again)

**Comment by riannella** [comment] 2017-06-22 05:24
So why then can't Bob and Alice have an odrl:Agreement to pay 10€ ?
(that make more semantic sense ;-)

What if you inherit a Set (with just a Duty in it) into an Agreement?

Policies need to have consistent Rules processing.

Perhaps we only allow Duties at the Policy level (like Perm/Prohibit) and it simply means that all the Duties need to be satisfied for all the Perms/Prohits in the Policy to be "in effect" ??

**Comment by simonstey** [comment] 2017-06-22 06:05
> So why then can't Bob and Alice have an odrl:Agreement to pay 10€ ?
(that make more semantic sense ;-)

it does, but Agreements have to have at least one Perm/Prohib. What would be the accompanying Permission? The use of those 10€? ;)

> What if you inherit a Set (with just a Duty in it) into an Agreement?

The same as if you inherit an Offer (having Rules with assigners only) into an Agreement, the Agreement would become invalid. (assuming inherit A into B means B inherits from A)

> Policies need to have consistent Rules processing.

I agree! But since we treat duties as black boxes anyway, we only have to know whether:
+ a duty is in effect -> it's in effect as long as it wasn't fulfilled 
+ a policy is in effect -> it's in effect as long as at least one of its rules is in effect

> Perhaps we ~~only~~ allow Duties at the Policy level (like Perm/Prohibit) and it simply means that all the Duties need to be satisfied for all the Perms/~~Prohits~~ in the Policy to be "in effect" ??

sounds great!! I would suggest though to:
1. keep the current cardinality restrictions on policy types as is
2. allow top-level duties for Offer/Agreement only, if there's at least one permission in the policy the duties can be assigned to 
3. still allow to define duties for permissions directly
4. at some point we may want to consider allowing duties to "switch **off**" prohibitions if they are fulfilled, but never to switch them **on** (you wouldn't pay 10 euro to be prohibited to do something).
5. (nitpicking) you **satisfy** a constraint, but **fulfill** a duty

**Comment by riannella** [comment] 2017-06-22 06:43
Cool..see what "fighting" for this gets ;-))

**Comment by nitmws** [comment] 2017-06-26 14:23
Re the discussion at the [call on 2017-06-26](https://www.w3.org/2016/poe/wiki/Meetings:Telecon20170626)

First to say: following this issue and also issue #154 it is hard to draw unambiguous conclusions. E.g. is this discussion about having Duty at the policy-level applying only to the subclass Set and not other subclasses? If: Set is defined as "represents any combination of Rules" and it leaves it open for what purpose a Set may be used. May Set be used to check if an assignee is permitted to take an action on an asset, or is a Set too unclear?

The concern I raised was about this case in the context of an Agreement:
A policy expresses: Asset 99 may be presented by (parts of) the Team 4711 but not by (parts of) the team 4712. And a Duty at the policy level requires to pay 5 EUR.

```
<http://example.com/policy:001>
    a odrl:Agreement;
    "duty": [{
            "action": "compensate",
            "constraint": [{
                "leftOperand": "payAmount",
                "operator": "eq",
                "rightOperand": "5.00",
                "unit": "https://www.currency-iso.org/dam/downloads/lists/list_one.xml#EUR"
            }],
    odrl:permission [
        a odrl:Permission ;
        odrl:target ex:asset99 ;
        odrl:action odrl:present ;        
        odrl:assignee ex:team4711
    ] ;
    odrl:prohibition [
        a odrl:Prohibition ;
        odrl:target ex:asset99 ;
        odrl:action odrl:present ;
        odrl:assignee ex:team4712
    ] .
```
The request for evaluation is: Ms Person987 wants to present Asset 99 - and she is partOf Team4712 - and the ODRL Policy http://example.com/policy:001 needs to be evaluated.

What can be concluded from that use case?
* the Prohibition of Policy 001 applies to the request: the asset, the action and the assignee (via partOf) match (= at least one of the permission/prohibition rules of this Policy applies)
* does the policy-level duty apply too?
   * if the IM defines it applies only if one of the permissions is in effect: no
  * if the IM defines it applies to the policy in case of any permission/prohibition is in effect: yes

Footnote:  @simonstey example at the call to use a policy-level duty for requiring to follow a specific legislation fits well as it applies to permissions and prohibitions in the same way. So "passive" duties fit, and "active" duties do not fit at the policy-level?

**Comment by riannella** [comment] 2017-06-27 05:37
My concern is that I don't want the semantics of Duty to change depending on **where** it is in the Policy.

And we (currently) make lots of assumptions on who the assignee is for the Duty (based on the Permission).

**Comment by riannella** [comment] 2017-07-04 01:06
@nitmws RE: Sets: we don't define the Set policy type with any specific semantics (unlike Offer, Agreement...)... So if your example above was a Set, then all we can say is that the Policy has 3 Rules...

But, it is an Agreement (lets assume there is an assigner as well ;-)

Currently, there is an underlying relationship between Duty and Permission....you need to fulfil the Duty to get the Permission...(and the Duty was always subordinate to the Permission, so that relationship was clearer)

With a Duty at the policy-level - it now needs to be **defined** as an independent Rule (it is currently defined with strong dependencies to Permission).

**Comment by riannella** [comment] 2017-07-07 05:45
I have update the Duty section to make it standalone, and added a new subsection that talks about Duties with Permissions. 

See: https://w3c.github.io/poe/model/#duty

NOTE: I have not changed any other part of the spec (yet).
I wanted to first see that this change is ok?

commit: 01624e81cbd41e7162368437055a1e67c4e7a8ac

**Comment by riannella** [comment] 2017-07-11 04:40
WG agreed to the above approach: https://www.w3.org/2017/07/10-poe-minutes

**Comment by simonstey** [comment] 2017-07-11 05:20
> WG agreed to the above approach: https://www.w3.org/2017/07/10-poe-minutes

\<nit-picking>not raising any objections against the proposal (yet) != formally agreeing to it\</nit-picking> ;)

**Comment by riannella** [comment] 2017-07-18 04:18
Updated the IM/Vocab to now support the obligation property for policy-level Duties.

commit: 36d1a6a91e33112737853239de78076764dac01c

**Closed as completed** 2017-08-07 12:46 UTC
Labels: Wide Review, Model
