### ISSUE TITLE
Actions for Rule

### ISSUE THREAD

**Issue by sereAbi** [w3c/poe#80] opened 2016-12-02 15:04 UTC
The Information Model only allows one Action per Rule - is it too limiting?

**Comment by simonstey** [comment] 2016-12-02 15:18
why would that be too limiting?

currently we can express -> 
<policy> odrl:permission odrl:pay, odrl:use .

**Comment by riannella** [comment] 2016-12-06 00:56
Closing this - as duplicate of #73

**Closed as completed by riannella** 2016-12-06 00:56 UTC
Labels: Editorial
