### ISSUE TITLE
whats's the rationale behind uids?

### ISSUE THREAD

**Issue by simonstey** [w3c/poe#174] opened 2017-05-11 14:03 UTC
why are they mandatory for concepts like Asset and Party but optional for Rules?

why do we call them uids?

related: #111

**Comment by riannella** [comment] 2017-05-15 06:08
If they are not mandatory for Asset and Party, then what Asset and Party are you referring to??

uid - unique identifier

**Comment by simonstey** [comment] 2017-05-15 07:06
> If they are not mandatory for Asset and Party, then what Asset and Party are you referring to??

if they are mandatory, you can't have blank nodes for assets/parties:

```turtle
<http://example.com/notValid> 
    a odrl:Offer ;   
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/asset:9898> ;
        odrl:action odrl:reproduce ;
        odrl:assigner [ 
            a odrl:Party ;
            foaf:name "Bob" ;
        ]
    ] .
```

**Comment by riannella** [comment] 2017-05-16 00:07
Would any real system do that?
That is, assign the permission to reproduce asset9898 to foaf:name "Bob"

**Comment by riannella** [comment] 2017-06-06 02:43
@simonstey do you have any more comments/feedback here?

**Comment by iherman** [comment] 2017-06-06 05:02
I agree with @simonstey : there seem to be genuine cases when blank nides are perfectly fine, and a mandatory uid would make this impossible. @riannella, I don't really understand your question:

> would any system do that?

The example of @simonstey may be translated as a permission to *any* party whose name is Bob. Sounds goid to me (of course, in real life, one would use a different property to uniquely identify a person, like social security number or similar, but tge structure is identical).

**Comment by simonstey** [comment] 2017-06-06 05:03
> Would any real system do that?
That is, assign the permission to reproduce asset9898 to foaf:name "Bob"

that's not what it says though.. it states that the `odrl:assigner` of  `<http://example.com/notValid>` is an individual of type `odrl:Party` with `foaf:name "Bob"`.

edit: was about to say what @iherman said, so +1 to that ;)

**Comment by riannella** [comment] 2017-06-06 06:15
@iherman you answered my question ;-)
In "real life" you would uniquely identify the party.

Identification of Parties and Assets is a fundamental principle of ODRL Policies.

@simonstey's example to me looks like a "back-door" for a party constraint:

"assigner": {
            "@type": "Party",
            "uid":  "http://all-the-people-of-world.org",
            "constraint": [{
                "leftOperand": "foaf:name",
                "operator": "eq",
                "rightOperand": "Bob"
            }],
        },

If the above is what the Policy wants to express, then we should (must) express it consistently throughout the ODRL information model.

**Comment by iherman** [comment] 2017-06-06 06:50
> In "real life" you would uniquely identify the party.
>
> Identification of Parties and Assets is a fundamental principle of ODRL Policies.

But that does not mean using `uid`, though my reaction is not coming from any practice in ODRL rather the general way vocabularies are used. The pattern of such simple blank node structures (David Booth referred to these as [“Well behaved RDF”](http://dbooth.org/2013/well-behaved-rdf/Booth-well-behaved-rdf.pdf)) is widespread. Also, in terms of description logic, if the predicate in use can be defined as uniquely identifying, e.g., a person, then the implicit identification of the node via the usage of that predicate is also perfectly fine. All this for saying that _requiring_ the presence of ID is way too restrictive for my taste...

**Comment by riannella** [comment] 2017-06-07 00:28
I don't have a problem with blank nodes - but all means use them....but the ODRL Info Model says you must uniquely identify the party/asset. Hence, the blank node requires the uid property.

You say "... then the implicit identification of the node via the usage of that predicate is also perfectly fine."
I would then ask, please explain how the blank node (with foaf:name Bob) implicitly does that?

In this world of Linked Data, identity is everything ;-)

**Comment by iherman** [comment] 2017-06-07 05:08
> I don't have a problem with blank nodes - but all means use them....but the ODRL Info Model says you must uniquely identify the party/asset. Hence, the blank node requires the uid property.
> 
Yeah well… then indeed we have a problem. This means the model includes a restriction that we may have a problem with…

I guess a MUST can be replaced by a SHOULD.
> You say "... then the implicit identification of the node via the usage of that predicate is also perfectly fine."
> I would then ask, please explain how the blank node (with foaf:name Bob) implicitly does that?
> 

If a predicate is declared to be inverse functional (which is not the case for foaf:name but just suppose this for a moment) then if 

```
A foaf:name "bob".
B foaf:name "bob".
```

then an OWL reasoner would deduce that 

```
A owl:sameAs B
```

You are right this is not identification in terms of assigning it an explicit `id`. But for the underlying goal that, I presume, this is mentioned in the model, this may be just enough.

**Comment by riannella** [comment] 2017-06-08 00:38
All that "reasoning" happens outside the scope of ODRL.

In essence a "should" would propose:

{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Agreement",
    "uid": "http://example.com/policy:1011",
    "permission": [{
        "target": "",
        "assigner": "",
        "assignee": "",
         "action": "play"
    }]
}

**Comment by simonstey** [comment] 2017-06-12 11:52
> In essence a "should" would propose:
>```json
>"@context": "http://www.w3.org/ns/odrl.jsonld",
>"@type": "Agreement",
>"uid": "http://example.com/policy:1011",
>"permission": [{
>"target": "",
>"assigner": "",
>"assignee": "",
>"action": "play"
>}]
>}
>```

no, not having a value at all is different from allowing blank nodes.

> I don't have a problem with blank nodes - but all means use them....**but the ODRL Info Model says you must uniquely identify the party/asset. Hence, the blank node requires the uid property.**

well OWL doesn't adhere to UNA anyway, cf. [4.7 Equality and Inequality of Individuals](https://www.w3.org/TR/owl2-primer/#Equality_and_Inequality_of_Individuals):
> OWL does not make the assumption that different names are names for different individuals.

```turtle
<http://example.com/policy:01> 
    a odrl:Policy ;   
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/asset:9898> ;
        odrl:action odrl:display ;
        odrl:assigner ex:Bob ;
    ] ; 
    odrl:permission [
        a odrl:Permission ;
        odrl:target <http://example.com/asset:9898> ;
        odrl:action odrl:print ;
        odrl:assignee ex:Bob2 ;
    ] .

ex:Bob owl:sameAs ex:Bob2 . 
```

**Comment by riannella** [comment] 2017-06-12 13:08
RESOLUTION: That for asset and party, we change the MUST for uids from MUST to SHOULD, adding a narrative that if you don't use UIDs, then the system needs its own method of identifying the asset or party

**Comment by riannella** [comment] 2017-06-13 03:06
Changes not made yet :-)

**Comment by riannella** [comment] 2017-06-13 03:16
Changes applied.

commit: 52149f9130c1303bafc780255d01491570c039b5

**Closed as completed** 2017-06-20 08:36 UTC
Labels: question, Model
